import os

BASE_URL = os.environ.get("BASE_URL", "https://web-agr.chitai-gorod.ru/web/api")
TOKEN = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3VzZXItcmlnaHQiLCJzdWIiOjIwNTIxMDM0LCJpYXQiOjE3ODA2MzQyODMsImV4cCI6MTc4MDYzNzg4MywidHlwZSI6MjAsImp0aSI6IjAxOWU5NjEyLWVlZDAtNzBlNi1iMTY2LWJhNWNlYWUzNTIwYiIsInJvbGVzIjoxMH0.LGtS9Ry2oRGlciZQLx-QejBRzTrhdYpiLbOJv6gaEi5u0rEDjfjYoCjsA4XqiIUNtFmKnianurMC1w5Bxmf3kauytD4j8PmTtkJ_xU2tbJHwN2kvjFDIoqVMETS-Hp3y1SPFOZLkt2cvzXxP02zlTJjmLI6PbkrrrTyTcZDmsb9kdr2Mgfc2HbDhDHRdKeJQxHwEZW-eMtcNjDEilUqN7tvN0fqlE0NHooe_5bqYDdGo7lkmlpfhrwk7fSBqZXK_FdELa8Gs_HRFL7Df0vG4B3fl_B70sS_wkjTqb2jwJd7m_S7weq-hdLj3_t-8OP0hR_Pjq1xyId9bvdUS1BBZzw"
