[pytest]
markers =
    critical: Критически важные тесты
    normal: Обычные тесты
    minor: Незначительные тесты
    smoke: Дымовое тестирование
    regression: Регрессионное тестирование

testpaths = test
python_files = *test*.py
python_functions = *test*
python_classes = *Test*

addopts = -v --strict-markers --tb=short