"""
Auto-generated by postman2pytest.
Source: Читай-город курсовая
Generated: 2026-06-03 05:22 UTC
DO NOT EDIT. Re-generate from the Postman collection instead.
"""

import pytest
import requests
from constants import BASE_URL, TOKEN
import allure


@allure.title("Удаление книги из избранного")
@allure.severity(allure.severity_level.CRITICAL)
def test_positive_delete_book_from_fav():
    """Тест удаления товара из избранного"""

    with allure.step("Добавить книгу в избранное"):
        book_id = 2517639
        url = f"{BASE_URL}/v1/bookmarks"
        headers = {'authorization': TOKEN}
        body = {"id": book_id, "adData": {"item_list_name": "search", "product_shelf": ""}}
        response = requests.post(url, headers=headers, json=body)

    with allure.step("Проверить, что книга успешно добавлена"):
        assert response.status_code == 201, (
            f"Expected 201, got {response.status_code}: {response.text[:200]}"
        )

    with allure.step("Удалить книгу из избранного"):
        url = f"{BASE_URL}/v1/bookmarks/{book_id}"
        response = requests.delete(url, headers=headers)

    with allure.step("Проверить, что книга успешно удалилена"):
        assert response.status_code == 204, (
            f"Expected 204, got {response.status_code}: {response.text[:200]}"
        )


@allure.title("Удаление книги из корзины")
@allure.severity(allure.severity_level.CRITICAL)
def test_positive_delete_book_from_cart():
    """Тест удаления товара из корзины"""

    with allure.step("Добавить книгу в корзину"):
        url = f"{BASE_URL}/v1/cart/product"
        headers = {'authorization': TOKEN}
        book_id = 2517637
        body = {"id": book_id, "adData": {"item_list_name": "search", "product_shelf": ""}}
        response = requests.post(url, headers=headers, json=body)

    with allure.step("Проверить, что книга успешно добавлена в корзину"):
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}: {response.text[:200]}"
        )

    with allure.step("Удалить книгу из корзины"):
        url = f"{BASE_URL}/v1/cart/product/242981113"
        response = requests.delete(url, headers=headers)

    with allure.step("Проверить, что книга успешно удаллена из корзины"):
        assert response.status_code == 204, (
            f"Expected 204, got {response.status_code}: {response.text[:200]}"
        )


@allure.title("Поиск книг по запросу 'paulo'")
@allure.severity(allure.severity_level.CRITICAL)
def test_positive_search_paulo():
    """Проверка поисковой строки"""

    with allure.step("Выполнить поиск по запросу 'paulo'"):
        url = f"{BASE_URL}/v2/search/search-phrase-suggests?phrase=paulo"
        headers = {'authorization': TOKEN}
        response = requests.get(url, headers=headers)

    with allure.step("Проверить, что поиск выполнен успешно"):
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}: {response.text[:200]}"
        )

    with allure.step("Проверить, что в результатах поиска есть 'paulo'"):
        response_body = response.json()
        assert "paulo" in str(response_body["included"]), (
            f'В результатах поиска получено: {response_body["included"]}'
        )


@allure.title("Добавление книги в корзину")
@allure.severity(allure.severity_level.CRITICAL)
def test_positive_add_book_to_cart():
    """Тест на добавление товара в корзину"""

    with allure.step("Отправить запрос на добавление книги в корзину"):
        url = f"{BASE_URL}/v1/cart/product"
        headers = {'authorization': TOKEN}
        book_id = 2517638
        body = {"id": book_id, "adData": {"item_list_name": "search", "product_shelf": ""}}
        response = requests.post(url, headers=headers, json=body)

    with allure.step("Проверить, что книга успешно добавлена в корзину"):
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}: {response.text[:200]}"
        )


@allure.title("Добавление книги в избранное без авторизации")
@allure.severity(allure.severity_level.CRITICAL)
def test_negative_add_book_in_fav_with_no_autorization():
    """Тест на добавление товара в закладки без авторизации"""

    with allure.step("Отправить запрос на добавление книги в избранное без токена"):
        url = f"{BASE_URL}/v1/bookmarks"
        headers = {}
        body = {"id": 2967760, "adData": {"item_list_name": "search", "product_shelf": ""}}
        response = requests.post(url, headers=headers, json=body)

    with allure.step("Проверить, что сервер вернул ошибку авторизации"):
        assert response.status_code == 401, (
            f"Expected 401, got {response.status_code}: {response.text[:200]}"
        )
